### ISSUE TITLE
Possible to have result listing with scrollbar support?

### ISSUE THREAD

**Issue by luaz** [tcrosen/twitter-bootstrap-typeahead#19]

**Comment by tcrosen** [comment]
Hi luaz, you should be able to achieve this quite easily by adding your own CSS.

Something like this should work:

```
.typeahead { height: 50px; overflow-y: auto; }
```

**Comment by luaz** [comment]
I believe the solution doesn't work because once the scroll-bar is clicked, the result listing is hidden.

**Comment by vigneshbhaskar** [comment]
I have the same problem. The listing gets closed.

**Comment by tgirardi** [comment]
This is due to the input loosing the focus.

The blur listener gets called when you click anywhere outside the input, including anywhere inside the dropdown menu and that listener makes that menu disappear.

Another problem with trying to get scrollbar support is that the menu will not scroll while navigating up and down the listing using the keyboard, so after going up or down several times your selection could be hidden, because it could be one of the "li" elements that are not inside the visible portion of the "ul" (you'll need to scroll manually to get the selected item to be shown again).

@tcrosen: Terry, (by the way: awesome plugin)

I believe that adding scrollbar support for the menu wouldn't be hard. I proppose:
1. Each click event on $menu must keep the focus on the input
2. If the click was done inside an "li" of the menu, then that element must be selected, and then the menu has to be closed. If not, nothing is done (that way click events on the scrollbar won't cause the menu to close).
3. If the selected element has at least a portion of it outside the visible area, then the menu has to scroll accordingly in order to keep the whole element inside that visible area.

I could help you with that, but I'm a little confused if I should work on the 2.0 branch or in the master branch.

Regards,
Tomás

**Comment by tgirardi** [comment]
About point 1 of my previous comment, I found out we would need to listen for mousedown event and not click. It seems that click is not fired when clicking on the scrollbar.

Also, a solution that works for me is setting a property called keepFocus to true on the mousedown event listener and then checking for the value of that property on the blur event listener. If it is true, then we change the focus to this.$element (the input), we reset keepFocus to false and don't proceed to closing the menu.

So, in "listen" method:

``` diff
@@ -411 +444 @@ function ($) {
-            this.$menu.on('click', $.proxy(this.click, this))
+            this.$menu.on('mousedown', $.proxy(this.click, this))
```

In "click" method:

``` diff
@@ -496,9 +533,12 @@ function ($) {
         //  Handles clicking on the results list
         //
         click: function (e) {
-            e.stopPropagation();
-            e.preventDefault();
-            this.select();
+            if(e.target.tagName == 'A'){
+              e.stopPropagation();
+              e.preventDefault();
+              this.select();
+            }
+            this.keepFocus = true;
         },

         //------------------------------------------------------------------
```

In "blur" method:

``` diff
@@ -484,11 +517,15 @@ function ($) {
             var that = this;
             e.stopPropagation();
             e.preventDefault();
+            if(this.keepFocus) {
+              that.$element.focus();
+              this.keepFocus = false;
+            }
             setTimeout(function () {
                 if (!that.$menu.is(':focus')) {
                   that.hide();
                 }
             }, 150)
         },
```

**Comment by tgirardi** [comment]
ooops.... one last modification: we need to set keepFocus to true only if e.target is not an anchor. Otherwise, if we select an item, then make the menu reappear and then make the input loose the focus, the menu wouldn't disappear as expected.

So, click method:

``` diff
@@ -496,9 +533,13 @@ function ($) {
         //  Handles clicking on the results list
         //
         click: function (e) {
-            e.stopPropagation();
-            e.preventDefault();
-            this.select();
+            if(e.target.tagName == 'A'){
+              e.stopPropagation();
+              e.preventDefault();
+              this.select();
+            } else {
+              this.keepFocus = true;
+            }
         },

         //------------------------------------------------------------------
```

**Comment by tgirardi** [comment]
I have a solution for point 3 also. However, it wasn't as easy at it seemed.

The mayor difficulty is that **after scrolling the mouseenter event will probably be fired**, this is because the mouse keeps still, but the element "behind" the mouse is moved because of the scroll. So, if the scrolling distance is bigger than the height of each "li" inside the menu, the mouse will go from one list item to another, triggering the "mousenter" event. The problem? The **mouseenter listener will change the active list item**, from the one selected by the prev() o next() method - _the correct one_ - to the list item into which the mouse has just entered.

My solution to that problem was to set a new property for Typeahed called avoidMouseEnter to true before each scrollTo(). Typeahead.mousenter will check if that variable is true and return without doing anything if that is the case. 

But we need something more... it could happen that we do a scroll without a mouseenter event being triggered (this is possible if the distance of the scroll is not enough to pass the threshold between one list item and the next / previous one). To solve this issue I have chosen to bind a "mousemove" event to the menu's "ul" (this.$menu). The handler for that event is responsible for reseting avoidMouseEnter to false... if we move the mouse, then handling any mouseenter that could happen after that should be done in the traditional way. That same handler also unbinds the listener at the end, to avoid keep handling subsequent mousemove events without any need to do so (mousemove events are "expensive" to handle because they are very common).

What do you think of this solution? I'll be grateful for any suggestion and critics

Now, the code:

For prev and next method:

``` diff
@@ -363,14 +395,37 @@ function ($) {
         //  Selects the next result
         //
         next: function (event) {
-            var active = this.$menu.find('.active').removeClass('active');
+            var that = this;
+            var $menu = that.$menu;
+            var active = $menu.find('.active');
             var next = active.next();
-
+            var menuHeight = $menu.innerHeight();
+            var bottomPosition;
+            
             if (!next.length) {
                next = $(this.$menu.find('li')[0]);
             }
-
+            
+            active.removeClass('active');
             next.addClass('active');
+            bottomPosition = next.position().top + next.height();
+            if(menuHeight < bottomPosition){
+                that.avoidMouseEnter = true;
+                $menu.on('mousemove',function(){
+                  that.avoidMouseEnter = false;
+                  $menu.off('mousemove');
+                });
+                $menu.scrollTop($menu.scrollTop() + bottomPosition - menuHeight);
+            }
         },

         //------------------------------------------------------------------
@@ -378,14 +433,37 @@ function ($) {
         //  Selects the previous result
         //
         prev: function (event) {
-            var active = this.$menu.find('.active').removeClass('active');
+            var that = this;
+            var $menu = that.$menu;
+            var active = $menu.find('.active');
             var prev = active.prev();
+            var menuScroll = $menu.scrollTop();
+            var topPosition;

             if (!prev.length) {
                 prev = this.$menu.find('li').last();
             }

+            active.removeClass('active');
             prev.addClass('active');
+            topPosition = menuScroll + prev.position().top;
+            if(menuScroll > topPosition){
+                that.avoidMouseEnter = true;
+                $menu.on('mousemove',function(){
+                  that.avoidMouseEnter = false;
+                  $menu.off('mousemove');
+                });
+                $menu.scrollTop(topPosition);
+            }
         },

         //=============================================================================================================
```

For mouseenter method:

``` diff
@@ -506,8 +601,18 @@ function ($) {
         //  Handles the mouse entering the results list
         //
         mouseenter: function (e) {
+            if(this.avoidMouseEnter) {
+              this.avoidMouseEnter = false;
+              return;
+            }
             this.$menu.find('.active').removeClass('active');
             $(e.currentTarget).addClass('active');
         }
     }
```

**Comment by tgirardi** [comment]
@luaz, @vigneshbhaskar : the pull request in my previous comment fixes this issue. would you like to try it and review it?

I've made an online demo (jsfiddle) for testing: http://jsfiddle.net/r44dt/

**Comment by atuttle** [comment]
:+1: The only issue I've seen with this fiddle is the one that's described in the fiddle body. It could be fixed by adjusting `scrollTop` property on the up-arrow-key like (I assume) is being done for the down-arrow-key.
